### ISSUE TITLE
Practica 1 Interfaz  Grafica En Figma

### ISSUE THREAD

**Issue by EvelynLopezz** [SistemasTecTlaxiaco/practicaprototipos-los-3-mosqueteros-topicos#2]
[Practica1_Evelyn_Melissa.pdf](https://github.com/SistemasTecTlaxiaco/practicaprototipos-los-3-mosqueteros-topicos/files/8178323/Practica1_Evelyn_Melissa.pdf)
https://www.figma.com/file/B9qj76sRiVePjDNRmfAmrw/Untitled?node-id=8%3A

**Comment by josealfredo79** [comment]
@EvelynLopezz La calificación debe ir aquí por favor a quien califico

**Comment by magaly1311** [comment]
18.4 % calificación de la practica
